printWidth: 88
trailingComma: 'es5'
tabWidth: 4
semi: false
singleQuote: true
arrowParens: 'avoid'
vueIndentScriptAndStyle: false
# overrides:
#   - files: "*.vue"
#     options:
#       parser: "vue"
