repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.1.0 # Use the ref you want to point at
      hooks:
          - id: trailing-whitespace
          - id: requirements-txt-fixer
    - repo: https://github.com/ambv/black
      rev: 19.10b0
      hooks:
          - id: black
            language_version: python3.6
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.3
      hooks:
          - id: flake8
            additional_dependencies: [flake8-bugbear]
    - repo: https://github.com/prettier/prettier
      rev: 2.0.5
      hooks:
          - id: prettier
            args: [--prose-wrap=always, --print-width=88]
