repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.1.0 # Use the ref you want to point at
      hooks:
          - id: trailing-whitespace
          - id: requirements-txt-fixer
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v2.3.0
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/ambv/black
      rev: 19.10b0
      hooks:
          - id: black
            language_version: python3.6
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.3
      hooks:
          - id: flake8
            additional_dependencies: [flake8-bugbear]
    - repo: https://github.com/prettier/prettier
      rev: 2.0.5
      hooks:
          - id: prettier
            args: [--prose-wrap=always, --print-width=88]
    - repo: local
      hooks:
          - id: frontend-tests
            name: run frontend tests (takes a minute or two)
            language: node
            # TODO: ensure runs on fresh machines without node
            entry:
                npm run test --prefix management/frontend/
                --scripts-prepend-node-path=true
            files: \.(json|myext)$
            stages: [push]
            always_run: true
            verbose: true
