version: '3.3'

services:
  # Service to get manager up and running
  replay-manager:
    command: npm run dev # TODO: just for development, remove before shipping
    image: cloud.canister.io:5000/seth/replay-manager:latest
    hostname: replay-manager
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      default:
    restart: "no"
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.role==manager'

  # Service to get ready to run a honeypot
  replay-honeypot:
    image: cloud.canister.io:5000/seth/replay-honeypot:latest
    network_mode: "host"
    ports:
      - 1437:1437 # change to 1437 when running many honeypots
    # used to start honeypot after the manager container
    depends_on:
      - replay-manager
    restart: "no"
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.role==worker'
        preferences:
          - spread: node.id

networks:
  # Default network for container-container communication
  default:
  # Lets a device adopt the network environment of the host machine
  outside:
    external:
      name: "host"
