version: '3.3'

services:
  # Service to get manager up and running
  replay-manager:
    image: cloud.canister.io:5000/seth/replay-manager:latest
    hostname: replay-manager
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      default:
    # Volume to keep database data external to the container
    volumes:
        - replay-db:/usr/src/frontend/.data
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.role==manager'
      restart_policy:
        condition: on-failure

  # Service to get ready to run a honeypot
  # replay-honeypot:
  #   image: cloud.canister.io:5000/seth/replay-honeypot:latest
  #   ports:
  #     - 1437:1437 # change to 1437 when running many honeypots
  #   networks:
  #     - default
  #     - outside
  #   # used to start honeypot after the manager container
  #   # depends_on:
  #   #   - replay-manager
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - 'node.role==worker'
  #       preferences:
  #         - spread: node.id
  #     restart_policy:
  #       condition: on-failure

networks:
  # Default network for container-container communication
  default:
  # Lets a device adopt the network environment of the host machine
  outside:
    external:
      name: "host"

volumes:
  replay-db:
