version: '3.3'

services:
  # Service to get a database up and running with CORS
  couchdb:
    image: bitnami/couchdb:3
    environment:
      # TODO: change this
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=couchdb
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.role==manager'
    networks:
      default:
    ports:
      - '5984:5984'
      - '4369:4369'
      - '9100:9100'
    volumes:
      - couchdb_data:/bitnami/couchdb
      - ${PWD}/local.ini:/opt/bitnami/couchdb/etc/local.d/cutom-local.ini

  # Optional service to interact with database visually
  fauxton:
    image: 3apaxicom/fauxton
    networks:
      default:
    ports:
      - '8000:8000'
    command:
      - sh
      - "-c"
      - "fauxton -c http://couchdb:5984"
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.role==manager'

  # Service to get manager up and running
  replay-manager:
    image: cloud.canister.io:5000/seth/replay-manager:latest
    hostname: replay-manager
    ports:
      - 8080:8080
    networks:
      default:
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.role==manager'
      restart_policy:
        condition: on-failure

  # Service to get ready to run a honeypot
  # replay-honeypot:
  #   image: cloud.canister.io:5000/seth/replay-honeypot:latest
  #   ports:
  #     - 1437:1437 # change to 1437 when running many honeypots
  #   networks:
  #     - default
  #     - outside
  #   # used to start honeypot after the manager container
  #   # depends_on:
  #   #   - replay-manager
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - 'node.role==worker'
  #       preferences:
  #         - spread: node.id
  #     restart_policy:
  #       condition: on-failure

networks:
  # Default network for container-container communication
  default:
  # Lets a device adopt the network environment of the host machine
  outside:
    external:
      name: "host"

volumes:
  replay-db:
  couchdb_data:
    driver: local
