# This file is for development and will not work with stack deploy

version: '3.7'

services:
  # Service to start a devault ubuntu container with ssh running
  # newpot:
  #   image: linuxserver/openssh-server
  #   container_name: openssh-server
  #   hostname: openssh-server
  #   ports:
  #     - 2222:2222
  #   networks:
  #     default:
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/New_York
  #     - PASSWORD_ACCESS=false
  #     - PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVtnZ/ax3m7dOKuYPULSCRnJyiKDDHHyBRWGMFCq/yHEI7B61VfqP69fsoklvAwF7aTHfDotiWaum5PwEs2W66oHDHTyO2U08YnSp6vk/4sHiuuioyJbUfG3DKkIQOALUwlq7YjS8JQCG6TK/Eu2MhqyD9M0YpSi30H/dgi4u2PzQHbgk3dgnDiRaG3PCA1lD6S6timbNmhLmtkV5EFNIXquIadDqOeoNORS/bTFeatAzcoYUzszfUoHdOLcvV8EKlZ3cDL3kRxRUFqS20ktZXDpynVrBPqJFuWWUfhzMERpBLejA5IgEdVUMEb5Kl8jGBgbtT6p4ZPPGB6y5wpAn5 root@6344607aa60b
  #     - SUDO_ACCESS=true
  #     - USER_PASSWORD=password
  #     - USER_NAME=linuxserver.io
  #   volumes:
  #     - replay-src:/src
  #   ports:
  #     - 2222:2222
  #   restart: unless-stopped

  # Service to get manager up and running
  replay-manager:
    build:
      context: './management'
      dockerfile: Dockerfile
    restart: "no"
    container_name: honeypot-manager
    # used when we want a blank container for testing also
    # depends_on:
    #   - newpot
    # volumes:
    #   - replay-src:/src
    # working_dir: /src/management/frontend # comment to use bundled source code (needs fresh image)
    # environment:
    #   - NODE_ENV=development

  # Service to get ready to run a honeypot
  replay-honeypot:
    image: cloud.canister.io:5000/seth/replay-honeypot:latest
    build:
      network: "host"
      context: './honeypots'
      dockerfile: Dockerfile
    restart: "no"
    container_name: honeypot # Only works with one honeypot
    hostname: honeypot # Only works with one honeypot
    ports:
      - 9998:9998 # change to 9998 ^^
    # volumes:
    #   - replay-src:/src
    # working_dir: /src/honeypots/honeypot # comment to use bundled source code (needs fresh image)
    # environment:
    #   - NODE_ENV=development

volumes:
  # This volume gives access to the source code for the system (runtime binding)
  replay-src:
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind
