version: '3.8'

services:
    # # Service to get a database up and running with CORS
    couchdb:
        image: bitnami/couchdb:3
        container_name: couchdb
        hostname: couchdb
        environment:
            - COUCHDB_USER=admin # TODO: change creds or use default: "admin"
            - COUCHDB_PASSWORD=couchdb # TODO: change creds or use default: "couchdb"
        ports:
            - 5984:5984
            - 4369:4369
            - 9100:9100
        volumes:
            # - couchdb_data:/bitnami/couchdb # make data persistant here
            - ./config/couch_defaults.ini:/opt/bitnami/couchdb/etc/local.d/cutom-local.ini
        deploy:
            replicas: 1
            placement:
                constraints:
                    - 'node.role==manager'

    # Service to get manager frontend up and running
    replay-manager:
        image: 127.0.0.1:5000/replay/replay-manager:latest
        container_name: manager
        hostname: replay-manager
        ports:
            - 8080:8080
        configs:
            - source: frontend_users_seed
              target: /frontend_users_seed.json
        depends_on:
            - couchdb
        deploy:
            replicas: 1
            placement:
                constraints:
                    - 'node.role==manager'
            restart_policy:
                condition: on-failure

    # Service (global) to deploy the actual honeypot instances
    replay-honeypot:
        image: 127.0.0.1:5000/replay/replay-honeypot:latest
        container_name: honeypot
        # Toggle if you want a specific hostname to appear in the logs
        # hostname: replay-honeypot
        environment:
            - DB_URL=http://honeypots:securehoneypassword@10.11.12.125:5984
        configs:
            - source: default_hp_config
              target: /default_hp_config.json
            - source: cert
              target: /cert.pem
        # Toggle this for waiting on couchdb to start
        depends_on:
            - couchdb
        networks:
            hostnet: {}
        deploy:
            # replicas: 1
            mode: global
            placement:
                max_replicas_per_node: 1
                # constraints:
                #     - 'node.role==manager'
                preferences:
                    - spread: node.id
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    memory: 1GB
                reservations:
                    memory: 100m

networks:
    # Network to allow honeypots to take over host networking
    hostnet:
        external: true
        name: host

configs:
    # Seed data for frontend auth database
    frontend_users_seed:
        file: ./config/frontend_users_seed.json
    # Seed data for honeypot configurations
    default_hp_config:
        file: ./config/default_hp_config.json
    #  Optional cert for TLS connections from the honeypots
    cert:
        file: ./config/cert.pem

volumes:
    # Persist data from couchdb
    couchdb_data:
        driver: local
