version: '3.8'

services:
    # Service to get manager frontend up and running
    replay-manager:
        image: 127.0.0.1:5000/replay/replay-manager:latest
        container_name: ReplayManager
        environment:
            - DB_URL=https://admin:couchdb@192.168.42.55:6984
            - SAML_URL=https://replay-honeypots-pra-dev.onelogin.com/trust/saml2/http-post/sso/2113e233-794d-498e-a9f5-298bde50ada7
        ports:
            - 8080:8080
            - 8443:8443
        deploy:
            mode: global
            placement:
                max_replicas_per_node: 1
                constraints:
                    - 'node.role==manager'
            restart_policy:
                condition: on-failure

    # Service (global) to deploy the actual honeypot instances
    replay-honeypot:
        image: 127.0.0.1:5000/replay/replay-honeypot:latest
        container_name: ReplayHoneypot
        # Toggle if you do not want this hostname to appear in the logs
        # hostname: replay-honeypot # Toggle for all logs to group together
        environment:
            - DB_URL=http://admin:couchdb@192.168.42.55:5984 # Toggle when in docker-compose mode | This line would need to be changed to the HTTPS endpoint when in production (non-self signed cert)
            # - DB_URL= # Use this to make honeypot crash becasue of unset DB_URL
            - PYTHONPATH=/usr/src/app/honeypot
        networks:
            - hostnet
        deploy:
            mode: global
            # replicas: 2
            placement:
                # Toggle to limit honeypot deployment to non-manager nodes
                constraints:
                    - 'node.role!=manager'
                preferences:
                    - spread: node.id
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    memory: 1GB
                reservations:
                    memory: 100m

networks:
    hostnet:
        external:
            name: host
