version: '3.3'

services:
    # Service to run swarm state visualizer
    # https://github.com/dockersamples/docker-swarm-visualizer
    viz:
        image: dockersamples/visualizer:stable
        ports:
            - 8082:8080
        stop_grace_period: 1m30s
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        deploy:
            placement:
                constraints:
                    - 'node.role==manager'
