# Different dockerfile to try and have a live, containerized environment for development
FROM node:14-alpine

# Get curl for healthcheck
RUN apk add --update --no-cache --virtual native-deps\
  g++ gcc libgcc libstdc++ linux-headers make python

# Get wait for it, for DB
RUN apk add --no-cache bash
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /opt/bin/
RUN chmod +x /opt/bin/wait-for-it.sh

# Install running deps
COPY ./frontend/package* ./
RUN npm install node-gyp deasync -g
RUN npm install --quiet --only=production && \

# Create Port Mappings for frontend & database
EXPOSE 8080
ENV PARCEL_WORKERS 1

# Image default start strategy
ENTRYPOINT ["/opt/bin/wait-for-it.sh", "-s", "-t", "0"]
CMD ["couchdb:5984", "--", "npm", "run", "dev2" ]
